Final_Project/Controllers/AdminController.cs
using Final_Project.Data;
using Final_Project.Models;
using Final_Project.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Final_Project.Controllers
{
    public class AdminController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly AppDbContext _DbContext;
        public AdminController(AppDbContext dbContext, IWebHostEnvironment webHostEnvironment)
        {
            this._DbContext = dbContext;
            this._webHostEnvironment = webHostEnvironment;
        }

        #region Products

        //Get All Product
        [HttpGet]
        public IActionResult Dashboard()
        {
            var products = _DbContext.Products.Include(c => c.Category).ToList();

            var ProductViewModels = products.Select(prod => new ProductViewModel
            {
                Id = prod.Id,
                Name = prod.Name,
                Description = prod.Description,
                Price = prod.Price,
                ImagePath = prod.ImagePath,
                Category = new CategoryViewModel
                {

                    Name = prod.Category.Name
                }
            })
                .ToList();

            return View(ProductViewModels);

        }

        // Get Products Form
        [HttpGet]
        public IActionResult Products()
        {

            ViewBag.Cat = _DbContext.Categories.ToList();
            return View();

        }

        // Create New Product
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel viewModel, IFormFile Image)
        {
            try
            {

                var product = new Product();
                if (viewModel != null)
                {
                    if (Image != null)
                    {
                        string folder = "Images/ProductsImages";
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(Image.FileName);
                        string filePath = Path.Combine(_webHostEnvironment.WebRootPath, folder, fileName);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            Image.CopyTo(stream);
                        }


                        product.ImagePath = Path.Combine(folder, fileName);
                        product.Id = viewModel.Id;
                        product.Name = viewModel.Name;
                        product.Description = viewModel.Description;
                        product.Price = viewModel.Price;
                        product.CategoryId = viewModel.CategoryId;

                        _DbContext.Products.Add(product);
                        _DbContext.SaveChanges();
                        return RedirectToAction(nameof(Dashboard));
                    }
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        //Delete Product
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProd(int id, ProductViewModel model)
        {
            try
            {
                var item = _DbContext.Products.Where(x => x.Id == id).FirstOrDefault();
                if (item != null)
                {
                    _DbContext.Remove(item);
                    _DbContext.SaveChanges();
                    return RedirectToAction(nameof(Dashboard));

                }
                return View();
            }
            catch
            {
                return View();
            }
        }
        #endregion


        #region Category
        //Get All Categories
        [HttpGet]
        public IActionResult Categories()
        {
            var Cats = _DbContext.Categories.ToList();

            var CatViewModels = Cats.Select(cat => new CategoryViewModel
            {
                Id = cat.Id,
                Name = cat.Name,

            }).ToList();

            return View(CatViewModels);

        }

        // Get Category Form
        [HttpGet]
        public ActionResult CreateCat()
        {

            return View();

        }
        // Create New Category
        [HttpPost]
        public ActionResult CreateCategory(CategoryViewModel viewModel)
        {

            var cat = new Category();
            if (viewModel != null)
            {

                cat.Id = viewModel.Id;
                cat.Name = viewModel.Name;

                _DbContext.Categories.Add(cat);
                _DbContext.SaveChanges();
                return RedirectToAction(nameof(Categories));

            }
            return View();
        }

        //Delete Category
        [HttpPost]
        public IActionResult DeleteCat(int id, CategoryViewModel model)
        {
            try
            {
                var item = _DbContext.Categories.Where(x => x.Id == id).FirstOrDefault();
                if (item != null)
                {
                    _DbContext.Remove(item);
                    _DbContext.SaveChanges();
                    return RedirectToAction(nameof(Categories));

                }
                return View();
            }
            catch
            {
                return View();
            }
        }
        #endregion


    }
}

Final_Project/Controllers/ProductController.cs
using Final_Project.Data;
using Final_Project.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Final_Project.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _DbContext;
        public ProductController(AppDbContext dbContext)
        {
            this._DbContext = dbContext;
        }
        public IActionResult Index()
        {
            var products = _DbContext.Products.Include(c => c.Category).ToList();

            var ProductViewModels = products.Select(prod => new ProductViewModel
            {
                Id = prod.Id,
                Name = prod.Name,
                Description = prod.Description,
                Price = prod.Price,
                ImagePath = prod.ImagePath,
                Category = new CategoryViewModel
                {

                    Name = prod.Category.Name
                }
            })
                .ToList();

            return View(ProductViewModels);
        }
    }
}

Final_Project/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/css/admin.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Final_Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
</head>
<body>
    <div class="wrapper" >
        <!-- Sidebar  -->
        <nav id="sidebar" >
            <div class="sidebar-header">
                <h4>Dashboard</h4>
            </div>

            <ul class="list-unstyled components">
                <p>Dummy Heading</p>
                <li class="active">
                    <a asp-action="Dashboard" asp-controller="Admin">
                        <i class="fas fa-tachometer-alt"></i> All Products
                    </a>
                </li>
                <li>
                    <a asp-action="Products" asp-controller="Admin">
                        <i class="fas fa-plus"></i> Add Product
                    </a>
                </li>
                <li>
                    <a asp-action="Categories" asp-controller="Admin">
                        <i class="fas fa-list"></i> All Categories
                    </a>
                </li>
                <li>
                    <a asp-action="CreateCat" asp-controller="Admin">
                        <i class="fas fa-plus"></i> Add Category
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-shopping-cart"></i> Orders
                    </a>
                </li>
            </ul>

         
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <a asp-controller="Home" asp-action="Index" class="btn btn-dark">Back to Home</a>
                    </div>
                </div>
            </nav>

          <main>
              @RenderBody()
          </main>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Final_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Final_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Final_Project.styles.css" asp-append-version="true" />
  
 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Final_Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">All Products</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <a class="btn btn-dark" asp-controller="Admin"  asp-action="Dashboard">DashBoard</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Final_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>